#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
  CREATE ROLE ${BITBUCKET_DB_USER} WITH LOGIN PASSWORD '${BITBUCKET_DB_PASSWORD}' VALID UNTIL 'infinity';
  CREATE DATABASE ${BITBUCKET_DB_NAME} WITH ENCODING='UTF8' OWNER=${BITBUCKET_DB_USER} CONNECTION LIMIT=-1;
EOSQL