#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
  CREATE ROLE ${CROWD_DB_USER} WITH LOGIN PASSWORD '${CROWD_DB_PASSWORD}' VALID UNTIL 'infinity';
  CREATE DATABASE ${CROWD_DB_NAME} WITH ENCODING='UTF8' OWNER=${CROWD_DB_USER} CONNECTION LIMIT=-1;
EOSQL