#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
  CREATE ROLE ${JIRA_DB_USER} WITH LOGIN PASSWORD '${JIRA_DB_PASSWORD}' VALID UNTIL 'infinity';
  CREATE DATABASE ${JIRA_DB_NAME} WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0 OWNER=${JIRA_DB_USER} CONNECTION LIMIT=-1;
EOSQL